apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nestjs-app
  namespace: dev-nest
  labels:
    release: prometheus   # подогнать под селектор вашего оператора
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nestjs-app
  namespaceSelector:
    matchNames: [dev-nest]
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
